//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : UserInterface.sm
//

 //
//


#include "UserInterface.h"
#include "UserInterfaceFSM.h"

using namespace statemap;

// Static class declarations.
UIMap_Reset UIMap::Reset("UIMap::Reset", 0);
UIMap_AddressDisplay UIMap::AddressDisplay("UIMap::AddressDisplay", 1);
UIMap_Menu UIMap::Menu("UIMap::Menu", 2);

void UserInterfaceState::BtnModePressed(UserInterfaceFSM& context)
{
    Default(context);
}

void UserInterfaceState::Ready(UserInterfaceFSM& context)
{
    Default(context);
}

void UserInterfaceState::Default(UserInterfaceFSM& context)
{
    assert(false);

}

void UIMap_Default::Ready(UserInterfaceFSM& context)
{


}

void UIMap_Default::BtnModePressed(UserInterfaceFSM& context)
{


}

void UIMap_Reset::Ready(UserInterfaceFSM& context)
{

    context.getState().Exit(context);
    context.setState(UIMap::AddressDisplay);
    context.getState().Entry(context);

}

void UIMap_AddressDisplay::BtnModePressed(UserInterfaceFSM& context)
{

    context.getState().Exit(context);
    context.setState(UIMap::Menu);
    context.getState().Entry(context);

}

//
// Local variables:
//  buffer-read-only: t
// End:
//
