//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : UserInterface.sm
//

#ifndef USERINTERFACEFSM_H
#define USERINTERFACEFSM_H


#define SMC_NO_EXCEPTIONS

#include <statemap.h>

// Forward declarations.
class UIMap;
class UIMap_Reset;
class UIMap_AddressDisplay;
class UIMap_Menu;
class UIMap_Default;
class UserInterfaceState;
class UserInterfaceFSM;
class UserInterface;

class UserInterfaceState :
    public statemap::State
{
public:

    UserInterfaceState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(UserInterfaceFSM&) {};
    virtual void Exit(UserInterfaceFSM&) {};

    virtual void BtnModePressed(UserInterfaceFSM& context);
    virtual void Ready(UserInterfaceFSM& context);

protected:

    virtual void Default(UserInterfaceFSM& context);
};

class UIMap
{
public:

    static UIMap_Reset Reset;
    static UIMap_AddressDisplay AddressDisplay;
    static UIMap_Menu Menu;
};

class UIMap_Default :
    public UserInterfaceState
{
public:

    UIMap_Default(const char * const name, const int stateId)
    : UserInterfaceState(name, stateId)
    {};

    virtual void Ready(UserInterfaceFSM& context);
    virtual void BtnModePressed(UserInterfaceFSM& context);
};

class UIMap_Reset :
    public UIMap_Default
{
public:
    UIMap_Reset(const char * const name, const int stateId)
    : UIMap_Default(name, stateId)
    {};

    virtual void Ready(UserInterfaceFSM& context);
};

class UIMap_AddressDisplay :
    public UIMap_Default
{
public:
    UIMap_AddressDisplay(const char * const name, const int stateId)
    : UIMap_Default(name, stateId)
    {};

    virtual void BtnModePressed(UserInterfaceFSM& context);
};

class UIMap_Menu :
    public UIMap_Default
{
public:
    UIMap_Menu(const char * const name, const int stateId)
    : UIMap_Default(name, stateId)
    {};

};

class UserInterfaceFSM :
    public statemap::FSMContext
{
public:

    explicit UserInterfaceFSM(UserInterface& owner)
    : FSMContext(UIMap::Reset),
      _owner(owner)
    {};

    UserInterfaceFSM(UserInterface& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline UserInterface& getOwner()
    {
        return (_owner);
    };

    inline UserInterfaceState& getState()
    {
        assert(_state != NULL);

        return static_cast<UserInterfaceState&>(*_state);
    };

    inline void BtnModePressed()
    {
        getState().BtnModePressed(*this);
    };

    inline void Ready()
    {
        getState().Ready(*this);
    };

private:
    UserInterface& _owner;
};


#endif // USERINTERFACEFSM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
